# This file describes the GitHub Actions workflow for continuous integration of Spike.
#
# See
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# for API reference documentation on this file format.

name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    name: Test Spike build (Ubuntu)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo xargs apt-get install -y < .github/workflows/apt-packages.txt

      - run: |
          ci-tests/build-spike
          ci-tests/test-spike

  test-macos:
    name: Test Spike build (MacOS)
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: xargs brew install < .github/workflows/brew-packages.txt

      - run: |
          ci-tests/build-spike
          ci-tests/test-spike
